"""Generate CP932 bat files."""
from pathlib import Path

stop_bat = (
    "@echo off\r\n"
    "setlocal\r\n"
    "cd /d \"%~dp0\"\r\n"
    "if exist .venv\\Scripts\\python.exe (\r\n"
    "    .venv\\Scripts\\python.exe scripts\\stop_server.py\r\n"
    ") else (\r\n"
    "    python scripts\\stop_server.py 2>nul\r\n"
    ")\r\n"
    "exit /b 0\r\n"
)

start_bat = (
    "@echo off\r\n"
    "setlocal enabledelayedexpansion\r\n"
    "cd /d \"%~dp0\"\r\n"
    "\r\n"
    "where python >nul 2>nul\r\n"
    "if errorlevel 1 goto :err_python\r\n"
    "where node >nul 2>nul\r\n"
    "if errorlevel 1 goto :err_node\r\n"
    "\r\n"
    "if not exist .venv\\Scripts\\python.exe (\r\n"
    "    echo [setup] Python仮想環境を作成しています...\r\n"
    "    python -m venv .venv\r\n"
    ")\r\n"
    "\r\n"
    ".venv\\Scripts\\python -c \"import fastapi\" >nul 2>nul\r\n"
    "if errorlevel 1 (\r\n"
    "    echo [setup] バックエンド依存パッケージをインストールしています...\r\n"
    "    .venv\\Scripts\\python -m pip install -r backend\\requirements.txt\r\n"
    ")\r\n"
    "\r\n"
    "if not exist frontend\\node_modules (\r\n"
    "    echo [setup] フロントエンド依存パッケージをインストールしています...\r\n"
    "    pushd frontend\r\n"
    "    call npm install\r\n"
    "    popd\r\n"
    ")\r\n"
    "\r\n"
    "if not exist frontend\\dist (\r\n"
    "    echo [setup] フロントエンドをビルドしています...\r\n"
    "    pushd frontend\r\n"
    "    call npm run build\r\n"
    "    popd\r\n"
    ")\r\n"
    "\r\n"
    "if not exist .env copy .env.example .env >nul\r\n"
    "if not exist data mkdir data\r\n"
    "if not exist logs mkdir logs\r\n"
    "\r\n"
    "if \"%BACKEND_PORT%\"==\"\" (\r\n"
    "    set BACKEND_PORT=8000\r\n"
    "    for /l %%P in (8000,1,8020) do (\r\n"
    "        netstat -ano | findstr /R /C:\":%%P .*LISTENING\" >nul 2>nul\r\n"
    "        if errorlevel 1 (\r\n"
    "            set BACKEND_PORT=%%P\r\n"
    "            goto :port_found\r\n"
    "        )\r\n"
    "    )\r\n"
    ")\r\n"
    ":port_found\r\n"
    "\r\n"
    "echo [起動] サーバーを起動しています (ポート !BACKEND_PORT!)...\r\n"
    ".venv\\Scripts\\python.exe scripts\\start_server.py !BACKEND_PORT!\r\n"
    "if errorlevel 1 (\r\n"
    "    echo [エラー] サーバーの起動に失敗しました。logs\\server.err.log を確認してください。\r\n"
    "    pause\r\n"
    "    exit /b 1\r\n"
    ")\r\n"
    "\r\n"
    "echo [起動] サーバーが起動しました (http://127.0.0.1:!BACKEND_PORT!)\r\n"
    "call :open_app\r\n"
    "endlocal\r\n"
    "exit /b 0\r\n"
    "\r\n"
    ":open_app\r\n"
    "if \"%MRA_NO_BROWSER%\"==\"1\" goto :eof\r\n"
    "set \"CHROME=\"\r\n"
    "if exist \"%ProgramFiles%\\Google\\Chrome\\Application\\chrome.exe\" set \"CHROME=%ProgramFiles%\\Google\\Chrome\\Application\\chrome.exe\"\r\n"
    "if exist \"%ProgramFiles(x86)%\\Google\\Chrome\\Application\\chrome.exe\" set \"CHROME=%ProgramFiles(x86)%\\Google\\Chrome\\Application\\chrome.exe\"\r\n"
    "if exist \"%LocalAppData%\\Google\\Chrome\\Application\\chrome.exe\" set \"CHROME=%LocalAppData%\\Google\\Chrome\\Application\\chrome.exe\"\r\n"
    "if defined CHROME (\r\n"
    "    start \"\" \"%CHROME%\" --app=\"http://127.0.0.1:%BACKEND_PORT%\"\r\n"
    ") else (\r\n"
    "    start \"\" \"http://127.0.0.1:%BACKEND_PORT%\"\r\n"
    ")\r\n"
    "goto :eof\r\n"
    "\r\n"
    ":err_python\r\n"
    "echo [エラー] Python が見つかりません。Python 3.10以上をインストールしてください: https://www.python.org\r\n"
    "pause\r\n"
    "exit /b 1\r\n"
    "\r\n"
    ":err_node\r\n"
    "echo [エラー] Node.js が見つかりません。Node.js 18以上をインストールしてください: https://nodejs.org\r\n"
    "pause\r\n"
    "exit /b 1\r\n"
)

setup_bat = (
    "@echo off\r\n"
    "setlocal enabledelayedexpansion\r\n"
    "cd /d \"%~dp0\"\r\n"
    "\r\n"
    "echo === セットアップを開始します ===\r\n"
    "\r\n"
    "set \"PYTHON_CMD=python\"\r\n"
    "where py >nul 2>nul\r\n"
    "if not errorlevel 1 set \"PYTHON_CMD=py -3\"\r\n"
    "\r\n"
    "%PYTHON_CMD% --version >nul 2>nul\r\n"
    "if errorlevel 1 goto :install_python\r\n"
    ":python_ok\r\n"
    "where node >nul 2>nul\r\n"
    "if errorlevel 1 goto :install_node\r\n"
    ":node_ok\r\n"
    "\r\n"
    "echo [1/5] Python仮想環境を作成しています...\r\n"
    "if not exist .venv\\Scripts\\python.exe (\r\n"
    "    %PYTHON_CMD% -m venv .venv\r\n"
    "    if errorlevel 1 (\r\n"
    "        echo [エラー] Python仮想環境の作成に失敗しました。\r\n"
    "        pause\r\n"
    "        exit /b 1\r\n"
    "    )\r\n"
    ")\r\n"
    "\r\n"
    "echo [2/5] バックエンド依存パッケージをインストールしています...\r\n"
    ".venv\\Scripts\\python.exe -m pip install -r backend\\requirements.txt\r\n"
    "if errorlevel 1 (\r\n"
    "    echo [エラー] バックエンドのインストールに失敗しました。\r\n"
    "    pause\r\n"
    "    exit /b 1\r\n"
    ")\r\n"
    "\r\n"
    "echo [3/5] フロントエンド依存パッケージをインストールしています...\r\n"
    "if not exist frontend\\node_modules (\r\n"
    "    pushd frontend\r\n"
    "    call npm install\r\n"
    "    if errorlevel 1 (\r\n"
    "        popd\r\n"
    "        echo [エラー] フロントエンドのインストールに失敗しました。\r\n"
    "        pause\r\n"
    "        exit /b 1\r\n"
    "    )\r\n"
    "    popd\r\n"
    ")\r\n"
    "\r\n"
    "echo [4/5] フロントエンドをビルドしています...\r\n"
    "if not exist frontend\\dist (\r\n"
    "    pushd frontend\r\n"
    "    call npm run build\r\n"
    "    if errorlevel 1 (\r\n"
    "        popd\r\n"
    "        echo [エラー] フロントエンドのビルドに失敗しました。\r\n"
    "        pause\r\n"
    "        exit /b 1\r\n"
    "    )\r\n"
    "    popd\r\n"
    ")\r\n"
    "\r\n"
    "echo [5/5] 設定ファイル・データフォルダを準備しています...\r\n"
    "if not exist .env copy .env.example .env >nul\r\n"
    "if not exist data mkdir data\r\n"
    "if not exist logs mkdir logs\r\n"
    "\r\n"
    "echo.\r\n"
    "echo ================================================================\r\n"
    "echo セットアップが完了しました。「起動.bat」を実行してアプリを開始してください。\r\n"
    "echo ================================================================\r\n"
    "pause\r\n"
    "exit /b 0\r\n"
    "\r\n"
    ":install_python\r\n"
    "echo [setup] Python が見つかりません。手動でインストールしてください: https://www.python.org/downloads/\r\n"
    "pause\r\n"
    "exit /b 1\r\n"
    "\r\n"
    ":install_node\r\n"
    "echo [setup] Node.js が見つかりません。手動でインストールしてください: https://nodejs.org/\r\n"
    "pause\r\n"
    "exit /b 1\r\n"
)

root = Path(__file__).resolve().parents[1]
(root / "終了.bat").write_text(stop_bat, encoding="cp932")
(root / "起動.bat").write_text(start_bat, encoding="cp932")
(root / "導入.bat").write_text(setup_bat, encoding="cp932")
print("Bat files written successfully in CP932.")
